feat: add Lark to repository
madoka773/flatpak pull request #84
Opened 2024-11-14 12:44 UTC by first-storm

2024-11-14 12:45 UTC, first-storm commented
This pull request introduces a new Flatpak package for the Lark application, including the necessary metadata and configuration files. The most important changes include adding a desktop entry, metadata information, and a YAML manifest file for the package.

Metadata and configuration:

* [`manifests/com.larksuite.Lark/com.larksuite.Lark.desktop`](diffhunk://#diff-58b83ac5ff896805c08aa387af321ac86f0705f4345ae18069d43ed75fc4a4d8R1-R21): Added a desktop entry for the Lark application, including details such as name, comment, execution command, and categories.
* [`manifests/com.larksuite.Lark/com.larksuite.Lark.metainfo.xml`](diffhunk://#diff-5037b682469fbb543581acd62b0262ff9573e0874ed97cfe24453a29a77cc4b2R1-R23): Added metadata information for the Lark application, including the developer's name, description, homepage URL, and recommended controls.
* [`manifests/com.larksuite.Lark/com.larksuite.Lark.yaml`](diffhunk://#diff-8267e8d778adadc2077b9781d7489d05c559d659db52e5b80affd7901e41e397R1-R63): Added a YAML manifest file for the Lark Flatpak package, specifying the app ID, runtime, SDK, build commands, and sources.

By the way, are you still maintaining this? Maybe we can work together.

2024-11-14 13:12 UTC, pugaizai reviewed
also add application id to workflows/update.yml build.yml

2024-11-14 13:12 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +      - install -D -t /app/lib/ /usr/lib/x86_64-linux-gnu/{libbfd-*.so,libsframe.so.1}
use bsdtar instead

2024-11-14 13:12 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +        url: https://sf16-va.larksuitecdn.com/obj/lark-artifact-storage/1d51a0a0/Lark-linux_x64-7.28.10.deb
aarch64 build

2024-11-14 13:12 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +finish-args:
tray icon?

2024-11-14 13:23 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +        url: https://sf16-va.larksuitecdn.com/obj/lark-artifact-storage/1d51a0a0/Lark-linux_x64-7.28.10.deb
我这里都是尽量要有arm版的

2024-11-14 13:31 UTC, first-storm commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +finish-args:
https://docs.flatpak.org/en/latest/desktop-integration.html

2024-11-14 13:55 UTC, pugaizai requested changes

2024-11-14 13:55 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +  - --talk-name=org.gnome.ScreenSaver
```suggestion
  - --talk-name=org.gnome.ScreenSaver
  - --talk-name=org.kde.StatusNotifierWatcher
  - --own-name=org.kde.*
```
你没发现这个软件有托盘的嘛？

2024-11-14 13:55 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +      - install -D -t /app/bin/ /usr/bin/ar
```suggestion
```

2024-11-14 13:55 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +      - aarch64
```suggestion
```

2024-11-14 13:59 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +        filename: Lark-linux-arm64.deb
```suggestion
        filename: Lark-linux.deb
```

2024-11-14 14:06 UTC, pugaizai requested changes

2024-11-14 14:06 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +  - --filesystem=home
这个权限希望修改一下，因为会在home文件夹拉💩

2024-11-14 23:37 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +  - --talk-name=org.gnome.ScreenSaver
可以使用`flatpak run --log-session-bus <app-id>`来找找看有没有漏的

2024-11-15 00:09 UTC, first-storm commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +      - install -D -t /app/bin/ /usr/bin/ar
为啥删掉这个

2024-11-15 00:10 UTC, first-storm commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +  - --filesystem=home
这没办法，因为这是文档软件

2024-11-15 00:11 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +      - install -D -t /app/bin/ /usr/bin/ar
你都用不上`ar`了还要来这个干嘛

2024-11-15 00:11 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +  - --filesystem=home
虽然但是，这应该是云文档软件

2024-11-15 00:12 UTC, pugaizai commented on manifests/com.larksuite.Lark/com.larksuite.Lark.yaml
> +  - --filesystem=home
限定在documents和download就好

2024-11-15 06:52 UTC, merged

2024-11-15 07:00 UTC, first-storm commented
I can't get this on GNOME. There is no errors while running with `flatpak run --log-session-bus <app-id>`.

2024-11-15 07:04 UTC, pugaizai commented
```
C3: -> org.freedesktop.DBus call org.freedesktop.DBus.NameHasOwner at /org/freedesktop/DBus
Filtering message due to arg0 org.kde.StatusNotifierWatcher, policy: 0 (required 1)
B-1: <- org.freedesktop.DBus return from C3
```

https://docs.flatpak.org/en/latest/desktop-integration.html

chapter StatusNotifier